/*
 * This source file was generated by the Gradle 'init' task
 */
package java_project;

import java.sql.Connection;

import main.java.java_project.utils.DatabaseConnection;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

   try {
        String sql = """
            CREATE TABLE IF NOT EXISTS trips (
                id INT AUTO_INCREMENT PRIMARY KEY,
                title VARCHAR(150) NOT NULL,
                description TEXT,
                destination VARCHAR(100) NOT NULL,
                start_date DATE NOT NULL,
                end_date DATE NOT NULL,
                price DECIMAL(10,2) NOT NULL,
                image_url VARCHAR(255),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB;
        """;
            Connection conn = DatabaseConnection.getInstance().getConnection();
            System.out.println("✅ Connected to MySQL successfully");
            Statement stmt = conn.createStatement();
            stmt.execute(sql);
            System.out.println("✅ Table 'trips' created successfully");
        } catch (Exception e) {
            e.printStackTrace();
        }

        System.out.println(new App().getGreeting());
    }
}
